/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4_inf3405;

import java.net.ServerSocket;
import java.text.NumberFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Simel
 */
public class Server extends javax.swing.JFrame {

    private static ServerSocket server_;
    
    private NumberFormat portFormat_;
    private String ipFormat_;
    private NumberFormat durationFormat_;
    
    private Pattern pattern_;
    private Matcher matcher_;
    /**
     * Creates new form Client
     */
    public Server() {
        initComponents();
        SetFormats();
    }
    
    /**
     * Create and and set up number and IP format
     */
    private void SetFormats() {
        
        portFormat_ = NumberFormat.getNumberInstance();
        
        ipFormat_ = "^([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." + 
                    "([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." + 
                    "([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." + 
                    "([01]?\\d\\d?|2[0-4]\\d|25[0-5])$"; // should actually be declared as static final
        
        durationFormat_ = NumberFormat.getInstance();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverPanel_ = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTextArea_ = new javax.swing.JTextArea();
        ipLabel_ = new javax.swing.JLabel();
        durationLabel_ = new javax.swing.JLabel();
        sendButton_ = new javax.swing.JButton();
        openSurveyButton_ = new javax.swing.JButton();
        portNumLabel_ = new javax.swing.JLabel();
        closeSurveyButton_ = new javax.swing.JButton();
        remainingLabel_ = new javax.swing.JLabel();
        remOutputLabel_ = new javax.swing.JLabel();
        portNumFTextField_ = new javax.swing.JFormattedTextField();
        ipFTextField_ = new javax.swing.JFormattedTextField();
        durationFTextField_ = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serverPanel_.setBorder(javax.swing.BorderFactory.createTitledBorder("Server"));
        serverPanel_.setName("Server"); // NOI18N

        msgTextArea_.setColumns(20);
        msgTextArea_.setRows(5);
        msgTextArea_.setName("QuestionTextArea"); // NOI18N
        jScrollPane1.setViewportView(msgTextArea_);

        ipLabel_.setText("IP Address:");

        durationLabel_.setText("Duration:");

        sendButton_.setText("SEND");

        openSurveyButton_.setText("OPEN SURVEY");

        portNumLabel_.setText("Port Number:");

        closeSurveyButton_.setText("CLOSE SURVEY");

        remainingLabel_.setText("Remaining:");

        remOutputLabel_.setText("jLabel4");
        remOutputLabel_.setMinimumSize(new java.awt.Dimension(104, 24));
        remOutputLabel_.setPreferredSize(new java.awt.Dimension(104, 24));

        portNumFTextField_.setMinimumSize(new java.awt.Dimension(104, 24));
        portNumFTextField_.setPreferredSize(new java.awt.Dimension(104, 24));

        ipFTextField_.setMinimumSize(new java.awt.Dimension(104, 24));
        ipFTextField_.setPreferredSize(new java.awt.Dimension(104, 24));

        durationFTextField_.setMinimumSize(new java.awt.Dimension(104, 24));
        durationFTextField_.setPreferredSize(new java.awt.Dimension(104, 24));

        javax.swing.GroupLayout serverPanel_Layout = new javax.swing.GroupLayout(serverPanel_);
        serverPanel_.setLayout(serverPanel_Layout);
        serverPanel_Layout.setHorizontalGroup(
            serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverPanel_Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(serverPanel_Layout.createSequentialGroup()
                        .addComponent(openSurveyButton_)
                        .addGap(18, 18, 18)
                        .addComponent(sendButton_, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeSurveyButton_))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serverPanel_Layout.createSequentialGroup()
                        .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(serverPanel_Layout.createSequentialGroup()
                                .addComponent(ipLabel_)
                                .addGap(18, 18, 18)
                                .addComponent(ipFTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(serverPanel_Layout.createSequentialGroup()
                                .addComponent(durationLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(durationFTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remainingLabel_)
                            .addComponent(portNumLabel_))
                        .addGap(18, 18, 18)
                        .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remOutputLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(portNumFTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        serverPanel_Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeSurveyButton_, openSurveyButton_});

        serverPanel_Layout.setVerticalGroup(
            serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverPanel_Layout.createSequentialGroup()
                .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serverPanel_Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portNumFTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ipFTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ipLabel_))
                        .addGap(20, 20, 20)
                        .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durationFTextField_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationLabel_)
                            .addComponent(remainingLabel_)
                            .addComponent(remOutputLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeSurveyButton_)
                            .addGroup(serverPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(openSurveyButton_, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sendButton_, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(serverPanel_Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(portNumLabel_)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        serverPanel_Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {durationLabel_, ipLabel_});

        serverPanel_Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {closeSurveyButton_, openSurveyButton_, sendButton_});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serverPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(serverPanel_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
        
       //server_ = new ServerSocket()
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeSurveyButton_;
    private static javax.swing.JFormattedTextField durationFTextField_;
    private javax.swing.JLabel durationLabel_;
    private static javax.swing.JFormattedTextField ipFTextField_;
    private javax.swing.JLabel ipLabel_;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msgTextArea_;
    private javax.swing.JButton openSurveyButton_;
    private javax.swing.JFormattedTextField portNumFTextField_;
    private javax.swing.JLabel portNumLabel_;
    private static javax.swing.JLabel remOutputLabel_;
    private javax.swing.JLabel remainingLabel_;
    private javax.swing.JButton sendButton_;
    private javax.swing.JPanel serverPanel_;
    // End of variables declaration//GEN-END:variables
}
